import path from 'node:path';
import { StorageKeyError } from './types.js';

/**
 * Storage keys are generated by the platform, never from user input:
 *   objects/<2 chars>/<2 chars>/<file id>
 * They are still strictly validated before touching any backend as defence in depth.
 */
const KEY_RE = /^[A-Za-z0-9][A-Za-z0-9_\-]*(\/[A-Za-z0-9][A-Za-z0-9_\-.]*)*$/;

export function assertSafeKey(key: string): void {
  if (
    typeof key !== 'string' ||
    key.length === 0 ||
    key.length > 512 ||
    key.includes('\0') ||
    key.includes('\\') ||
    key.split('/').some((seg) => seg === '' || seg === '.' || seg === '..') ||
    !KEY_RE.test(key)
  ) {
    throw new StorageKeyError('Invalid storage key');
  }
}

export function objectKeyForFile(fileId: string): string {
  // Shard by the random (tail) part of the ULID to spread entries across directories.
  const tail = fileId.slice(-4).toLowerCase();
  const key = `objects/${tail.slice(0, 2)}/${tail.slice(2, 4)}/${fileId}`;
  assertSafeKey(key);
  return key;
}

/**
 * Resolves `key` beneath `root` and guarantees the result cannot escape it,
 * regardless of `..`, absolute paths, drive letters or encoded separators.
 */
export function safeResolve(root: string, key: string): string {
  assertSafeKey(key);
  const absRoot = path.resolve(root);
  const target = path.resolve(absRoot, ...key.split('/'));
  const rel = path.relative(absRoot, target);
  if (!rel || rel.startsWith('..') || path.isAbsolute(rel)) {
    throw new StorageKeyError('Storage key escapes the storage root');
  }
  return target;
}
