# Code generated by scripts/generate-sdks.mjs from the OpenAPI document. DO NOT EDIT.
# ruff: noqa: E501
from typing import Any, Dict, Optional
from urllib.parse import quote as _quote

from ._core import CdnCore


def _q(v: str) -> str:
    return _quote(str(v), safe="")


class CdnClient(CdnCore):
    """CDNPanel API client. Every method maps to one REST endpoint."""

    def identify_the_caller(self) -> Any:
        """Identify the caller (GET /api/v1/me)."""
        return self._request("GET", f"/api/v1/me")

    def analytics_overview(self, query: Optional[Dict[str, Any]] = None) -> Any:
        """Analytics overview (GET /api/v1/analytics)."""
        return self._request("GET", f"/api/v1/analytics", query=query)

    def bandwidth_usage(self, query: Optional[Dict[str, Any]] = None) -> Any:
        """Bandwidth usage (GET /api/v1/analytics/bandwidth)."""
        return self._request("GET", f"/api/v1/analytics/bandwidth", query=query)

    def analytics_for_a_file(self, id: str, query: Optional[Dict[str, Any]] = None) -> Any:
        """Analytics for a file (GET /api/v1/analytics/files/{id})."""
        return self._request("GET", f"/api/v1/analytics/files/{_q(id)}", query=query)

    def global_delivery_map_data(self, query: Optional[Dict[str, Any]] = None) -> Any:
        """Global delivery map data (GET /api/v1/analytics/geo)."""
        return self._request("GET", f"/api/v1/analytics/geo", query=query)

    def update_a_cache_rule(self, id: str, body: Optional[Dict[str, Any]] = None) -> Any:
        """Update a cache rule (PATCH /api/v1/cache-rules/{id})."""
        return self._request("PATCH", f"/api/v1/cache-rules/{_q(id)}", body=body)

    def delete_a_cache_rule(self, id: str) -> Any:
        """Delete a cache rule (DELETE /api/v1/cache-rules/{id})."""
        return self._request("DELETE", f"/api/v1/cache-rules/{_q(id)}")

    def pre_warm_the_edge_cache(self, body: Optional[Dict[str, Any]] = None) -> Any:
        """Pre-warm the edge cache (POST /api/v1/cache/prewarm)."""
        return self._request("POST", f"/api/v1/cache/prewarm", body=body)

    def purge_the_cdn_cache(self, body: Optional[Dict[str, Any]] = None) -> Any:
        """Purge the CDN cache (POST /api/v1/cache/purge)."""
        return self._request("POST", f"/api/v1/cache/purge", body=body)

    def purge_history(self, query: Optional[Dict[str, Any]] = None) -> Any:
        """Purge history (GET /api/v1/cache/purges)."""
        return self._request("GET", f"/api/v1/cache/purges", query=query)

    def cache_statistics(self, query: Optional[Dict[str, Any]] = None) -> Any:
        """Cache statistics (GET /api/v1/cache/stats)."""
        return self._request("GET", f"/api/v1/cache/stats", query=query)

    def explain_a_files_cache_policy(self, id: str) -> Any:
        """Explain a file’s cache policy (GET /api/v1/files/{id}/cache)."""
        return self._request("GET", f"/api/v1/files/{_q(id)}/cache")

    def create_a_cache_rule(self, id: str, body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a cache rule (POST /api/v1/zones/{id}/cache-rules)."""
        return self._request("POST", f"/api/v1/zones/{_q(id)}/cache-rules", body=body)

    def issue_a_signed_access_cookie(self, body: Optional[Dict[str, Any]] = None) -> Any:
        """Issue a signed access cookie (POST /api/v1/signed-cookies)."""
        return self._request("POST", f"/api/v1/signed-cookies", body=body)

    def list_and_search_files(self, query: Optional[Dict[str, Any]] = None) -> Any:
        """List and search files (GET /api/v1/files)."""
        return self._request("GET", f"/api/v1/files", query=query)

    def upload_a_file(self, files: Dict[str, Any], fields: Optional[Dict[str, str]] = None) -> Any:
        """Upload a file (POST /api/v1/files)."""
        return self._request("POST", f"/api/v1/files", files=files, fields=fields)

    def get_a_file(self, id: str) -> Any:
        """Get a file (GET /api/v1/files/{id})."""
        return self._request("GET", f"/api/v1/files/{_q(id)}")

    def update_a_file(self, id: str, body: Optional[Dict[str, Any]] = None) -> Any:
        """Update a file (PATCH /api/v1/files/{id})."""
        return self._request("PATCH", f"/api/v1/files/{_q(id)}", body=body)

    def delete_a_file(self, id: str, query: Optional[Dict[str, Any]] = None) -> Any:
        """Delete a file (DELETE /api/v1/files/{id})."""
        return self._request("DELETE", f"/api/v1/files/{_q(id)}", query=query)

    def copy_a_file(self, id: str, body: Optional[Dict[str, Any]] = None) -> Any:
        """Copy a file (POST /api/v1/files/{id}/copy)."""
        return self._request("POST", f"/api/v1/files/{_q(id)}/copy", body=body)

    def download_a_file(self, id: str, query: Optional[Dict[str, Any]] = None) -> Any:
        """Download a file (GET /api/v1/files/{id}/download)."""
        return self._request("GET", f"/api/v1/files/{_q(id)}/download", query=query, raw_response=True)

    def get_file_metadata(self, id: str) -> Any:
        """Get file metadata (GET /api/v1/files/{id}/metadata)."""
        return self._request("GET", f"/api/v1/files/{_q(id)}/metadata")

    def move_a_file(self, id: str, body: Optional[Dict[str, Any]] = None) -> Any:
        """Move a file (POST /api/v1/files/{id}/move)."""
        return self._request("POST", f"/api/v1/files/{_q(id)}/move", body=body)

    def list_folders(self, query: Optional[Dict[str, Any]] = None) -> Any:
        """List folders (GET /api/v1/folders)."""
        return self._request("GET", f"/api/v1/folders", query=query)

    def create_a_folder(self, body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a folder (POST /api/v1/folders)."""
        return self._request("POST", f"/api/v1/folders", body=body)

    def get_a_folder(self, id: str) -> Any:
        """Get a folder (GET /api/v1/folders/{id})."""
        return self._request("GET", f"/api/v1/folders/{_q(id)}")

    def update_move_a_folder(self, id: str, body: Optional[Dict[str, Any]] = None) -> Any:
        """Update / move a folder (PATCH /api/v1/folders/{id})."""
        return self._request("PATCH", f"/api/v1/folders/{_q(id)}", body=body)

    def delete_a_folder(self, id: str, query: Optional[Dict[str, Any]] = None) -> Any:
        """Delete a folder (DELETE /api/v1/folders/{id})."""
        return self._request("DELETE", f"/api/v1/folders/{_q(id)}", query=query)

    def list_image_variants(self, id: str) -> Any:
        """List image variants (GET /api/v1/files/{id}/variants)."""
        return self._request("GET", f"/api/v1/files/{_q(id)}/variants")

    def delete_cached_image_variants(self, id: str) -> Any:
        """Delete cached image variants (DELETE /api/v1/files/{id}/variants)."""
        return self._request("DELETE", f"/api/v1/files/{_q(id)}/variants")

    def sign_an_image_transformation_url(self, body: Optional[Dict[str, Any]] = None) -> Any:
        """Sign an image transformation URL (POST /api/v1/images/sign)."""
        return self._request("POST", f"/api/v1/images/sign", body=body)

    def list_media_renditions(self, id: str, query: Optional[Dict[str, Any]] = None) -> Any:
        """List media renditions (GET /api/v1/files/{id}/media)."""
        return self._request("GET", f"/api/v1/files/{_q(id)}/media", query=query)

    def generate_media_renditions(self, id: str, body: Optional[Dict[str, Any]] = None) -> Any:
        """Generate media renditions (POST /api/v1/files/{id}/media/process)."""
        return self._request("POST", f"/api/v1/files/{_q(id)}/media/process", body=body)

    def create_a_share_link(self, id: str, body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a share link (POST /api/v1/files/{id}/shares)."""
        return self._request("POST", f"/api/v1/files/{_q(id)}/shares", body=body)

    def list_share_links(self, query: Optional[Dict[str, Any]] = None) -> Any:
        """List share links (GET /api/v1/shares)."""
        return self._request("GET", f"/api/v1/shares", query=query)

    def get_a_share_link_with_its_access_log(self, id: str) -> Any:
        """Get a share link with its access log (GET /api/v1/shares/{id})."""
        return self._request("GET", f"/api/v1/shares/{_q(id)}")

    def update_a_share_link(self, id: str, body: Optional[Dict[str, Any]] = None) -> Any:
        """Update a share link (PATCH /api/v1/shares/{id})."""
        return self._request("PATCH", f"/api/v1/shares/{_q(id)}", body=body)

    def revoke_a_share_link(self, id: str) -> Any:
        """Revoke a share link (POST /api/v1/shares/{id}/revoke)."""
        return self._request("POST", f"/api/v1/shares/{_q(id)}/revoke")

    def create_a_signed_url(self, id: str, body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a signed URL (POST /api/v1/files/{id}/signed-url)."""
        return self._request("POST", f"/api/v1/files/{_q(id)}/signed-url", body=body)

    def upload_one_or_more_files(self, files: Dict[str, Any], fields: Optional[Dict[str, str]] = None) -> Any:
        """Upload one or more files (POST /api/v1/uploads)."""
        return self._request("POST", f"/api/v1/uploads", files=files, fields=fields)

    def get_upload_status(self, id: str) -> Any:
        """Get upload status (GET /api/v1/uploads/{id})."""
        return self._request("GET", f"/api/v1/uploads/{_q(id)}")

    def abort_a_chunked_upload(self, id: str) -> Any:
        """Abort a chunked upload (DELETE /api/v1/uploads/{id})."""
        return self._request("DELETE", f"/api/v1/uploads/{_q(id)}")

    def upload_a_chunk(self, id: str, data: bytes, query: Optional[Dict[str, Any]] = None) -> Any:
        """Upload a chunk (POST /api/v1/uploads/{id}/chunk)."""
        return self._request("POST", f"/api/v1/uploads/{_q(id)}/chunk", query=query, data=data)

    def complete_a_chunked_upload(self, id: str) -> Any:
        """Complete a chunked upload (POST /api/v1/uploads/{id}/complete)."""
        return self._request("POST", f"/api/v1/uploads/{_q(id)}/complete")

    def start_a_chunked_resumable_upload(self, body: Optional[Dict[str, Any]] = None) -> Any:
        """Start a chunked (resumable) upload (POST /api/v1/uploads/init)."""
        return self._request("POST", f"/api/v1/uploads/init", body=body)

    def usage_for_a_scope(self, query: Optional[Dict[str, Any]] = None) -> Any:
        """Usage for a scope (GET /api/v1/usage)."""
        return self._request("GET", f"/api/v1/usage", query=query)

    def restore_a_file_from_the_recycle_bin(self, id: str, body: Optional[Dict[str, Any]] = None) -> Any:
        """Restore a file from the recycle bin (POST /api/v1/files/{id}/restore)."""
        return self._request("POST", f"/api/v1/files/{_q(id)}/restore", body=body)

    def list_file_revisions(self, id: str) -> Any:
        """List file revisions (GET /api/v1/files/{id}/versions)."""
        return self._request("GET", f"/api/v1/files/{_q(id)}/versions")

    def upload_a_new_revision(self, id: str, files: Dict[str, Any], fields: Optional[Dict[str, str]] = None) -> Any:
        """Upload a new revision (POST /api/v1/files/{id}/versions)."""
        return self._request("POST", f"/api/v1/files/{_q(id)}/versions", files=files, fields=fields)

    def delete_a_revision(self, id: str, version: str) -> Any:
        """Delete a revision (DELETE /api/v1/files/{id}/versions/{version})."""
        return self._request("DELETE", f"/api/v1/files/{_q(id)}/versions/{_q(version)}")

    def roll_back_to_a_revision(self, id: str, version: str) -> Any:
        """Roll back to a revision (POST /api/v1/files/{id}/versions/{version}/restore)."""
        return self._request("POST", f"/api/v1/files/{_q(id)}/versions/{_q(version)}/restore")

    def list_the_recycle_bin(self, query: Optional[Dict[str, Any]] = None) -> Any:
        """List the recycle bin (GET /api/v1/trash)."""
        return self._request("GET", f"/api/v1/trash", query=query)

    def permanently_delete_a_file_from_the_recycle_bin(self, id: str) -> Any:
        """Permanently delete a file from the recycle bin (DELETE /api/v1/trash/{id})."""
        return self._request("DELETE", f"/api/v1/trash/{_q(id)}")

    def make_a_domain_primary(self, id: str, body: Optional[Dict[str, Any]] = None) -> Any:
        """Make a domain primary (PATCH /api/v1/domains/{id})."""
        return self._request("PATCH", f"/api/v1/domains/{_q(id)}", body=body)

    def remove_a_domain(self, id: str) -> Any:
        """Remove a domain (DELETE /api/v1/domains/{id})."""
        return self._request("DELETE", f"/api/v1/domains/{_q(id)}")

    def run_a_domain_health_check(self, id: str) -> Any:
        """Run a domain health check (POST /api/v1/domains/{id}/check)."""
        return self._request("POST", f"/api/v1/domains/{_q(id)}/check")

    def verify_a_domain(self, id: str) -> Any:
        """Verify a domain (POST /api/v1/domains/{id}/verify)."""
        return self._request("POST", f"/api/v1/domains/{_q(id)}/verify")

    def list_projects(self) -> Any:
        """List projects (GET /api/v1/projects)."""
        return self._request("GET", f"/api/v1/projects")

    def list_zones(self, query: Optional[Dict[str, Any]] = None) -> Any:
        """List zones (GET /api/v1/zones)."""
        return self._request("GET", f"/api/v1/zones", query=query)

    def create_a_zone(self, body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a zone (POST /api/v1/zones)."""
        return self._request("POST", f"/api/v1/zones", body=body)

    def get_a_zone(self, id: str) -> Any:
        """Get a zone (GET /api/v1/zones/{id})."""
        return self._request("GET", f"/api/v1/zones/{_q(id)}")

    def update_a_zone(self, id: str, body: Optional[Dict[str, Any]] = None) -> Any:
        """Update a zone (PATCH /api/v1/zones/{id})."""
        return self._request("PATCH", f"/api/v1/zones/{_q(id)}", body=body)

    def add_a_custom_domain(self, id: str, body: Optional[Dict[str, Any]] = None) -> Any:
        """Add a custom domain (POST /api/v1/zones/{id}/domains)."""
        return self._request("POST", f"/api/v1/zones/{_q(id)}/domains", body=body)

    def replication_status(self, id: str) -> Any:
        """Replication status (GET /api/v1/zones/{id}/replication)."""
        return self._request("GET", f"/api/v1/zones/{_q(id)}/replication")
