// Code generated by scripts/generate-sdks.mjs from the OpenAPI document. DO NOT EDIT.

package cdnpanel

import (
	"context"
	"fmt"
	"net/url"
)

var _ = fmt.Sprintf

// IdentifyTheCaller: Identify the caller (GET /api/v1/me).
func (c *Client) IdentifyTheCaller(ctx context.Context) (*Response, error) {
	return c.do(ctx, "GET", "/api/v1/me", nil, nil, nil, nil)
}

// AnalyticsOverview: Analytics overview (GET /api/v1/analytics).
func (c *Client) AnalyticsOverview(ctx context.Context, query url.Values) (*Response, error) {
	return c.do(ctx, "GET", "/api/v1/analytics", query, nil, nil, nil)
}

// BandwidthUsage: Bandwidth usage (GET /api/v1/analytics/bandwidth).
func (c *Client) BandwidthUsage(ctx context.Context, query url.Values) (*Response, error) {
	return c.do(ctx, "GET", "/api/v1/analytics/bandwidth", query, nil, nil, nil)
}

// AnalyticsForAFile: Analytics for a file (GET /api/v1/analytics/files/{id}).
func (c *Client) AnalyticsForAFile(ctx context.Context, id string, query url.Values) (*Response, error) {
	return c.do(ctx, "GET", fmt.Sprintf("/api/v1/analytics/files/%s", url.PathEscape(id)), query, nil, nil, nil)
}

// GlobalDeliveryMapData: Global delivery map data (GET /api/v1/analytics/geo).
func (c *Client) GlobalDeliveryMapData(ctx context.Context, query url.Values) (*Response, error) {
	return c.do(ctx, "GET", "/api/v1/analytics/geo", query, nil, nil, nil)
}

// UpdateACacheRule: Update a cache rule (PATCH /api/v1/cache-rules/{id}).
func (c *Client) UpdateACacheRule(ctx context.Context, id string, body any) (*Response, error) {
	return c.do(ctx, "PATCH", fmt.Sprintf("/api/v1/cache-rules/%s", url.PathEscape(id)), nil, body, nil, nil)
}

// DeleteACacheRule: Delete a cache rule (DELETE /api/v1/cache-rules/{id}).
func (c *Client) DeleteACacheRule(ctx context.Context, id string) (*Response, error) {
	return c.do(ctx, "DELETE", fmt.Sprintf("/api/v1/cache-rules/%s", url.PathEscape(id)), nil, nil, nil, nil)
}

// PreWarmTheEdgeCache: Pre-warm the edge cache (POST /api/v1/cache/prewarm).
func (c *Client) PreWarmTheEdgeCache(ctx context.Context, body any) (*Response, error) {
	return c.do(ctx, "POST", "/api/v1/cache/prewarm", nil, body, nil, nil)
}

// PurgeTheCdnCache: Purge the CDN cache (POST /api/v1/cache/purge).
func (c *Client) PurgeTheCdnCache(ctx context.Context, body any) (*Response, error) {
	return c.do(ctx, "POST", "/api/v1/cache/purge", nil, body, nil, nil)
}

// PurgeHistory: Purge history (GET /api/v1/cache/purges).
func (c *Client) PurgeHistory(ctx context.Context, query url.Values) (*Response, error) {
	return c.do(ctx, "GET", "/api/v1/cache/purges", query, nil, nil, nil)
}

// CacheStatistics: Cache statistics (GET /api/v1/cache/stats).
func (c *Client) CacheStatistics(ctx context.Context, query url.Values) (*Response, error) {
	return c.do(ctx, "GET", "/api/v1/cache/stats", query, nil, nil, nil)
}

// ExplainAFilesCachePolicy: Explain a file’s cache policy (GET /api/v1/files/{id}/cache).
func (c *Client) ExplainAFilesCachePolicy(ctx context.Context, id string) (*Response, error) {
	return c.do(ctx, "GET", fmt.Sprintf("/api/v1/files/%s/cache", url.PathEscape(id)), nil, nil, nil, nil)
}

// CreateACacheRule: Create a cache rule (POST /api/v1/zones/{id}/cache-rules).
func (c *Client) CreateACacheRule(ctx context.Context, id string, body any) (*Response, error) {
	return c.do(ctx, "POST", fmt.Sprintf("/api/v1/zones/%s/cache-rules", url.PathEscape(id)), nil, body, nil, nil)
}

// IssueASignedAccessCookie: Issue a signed access cookie (POST /api/v1/signed-cookies).
func (c *Client) IssueASignedAccessCookie(ctx context.Context, body any) (*Response, error) {
	return c.do(ctx, "POST", "/api/v1/signed-cookies", nil, body, nil, nil)
}

// ListAndSearchFiles: List and search files (GET /api/v1/files).
func (c *Client) ListAndSearchFiles(ctx context.Context, query url.Values) (*Response, error) {
	return c.do(ctx, "GET", "/api/v1/files", query, nil, nil, nil)
}

// UploadAFile: Upload a file (POST /api/v1/files).
func (c *Client) UploadAFile(ctx context.Context, form *Multipart) (*Response, error) {
	return c.do(ctx, "POST", "/api/v1/files", nil, nil, form, nil)
}

// GetAFile: Get a file (GET /api/v1/files/{id}).
func (c *Client) GetAFile(ctx context.Context, id string) (*Response, error) {
	return c.do(ctx, "GET", fmt.Sprintf("/api/v1/files/%s", url.PathEscape(id)), nil, nil, nil, nil)
}

// UpdateAFile: Update a file (PATCH /api/v1/files/{id}).
func (c *Client) UpdateAFile(ctx context.Context, id string, body any) (*Response, error) {
	return c.do(ctx, "PATCH", fmt.Sprintf("/api/v1/files/%s", url.PathEscape(id)), nil, body, nil, nil)
}

// DeleteAFile: Delete a file (DELETE /api/v1/files/{id}).
func (c *Client) DeleteAFile(ctx context.Context, id string, query url.Values) (*Response, error) {
	return c.do(ctx, "DELETE", fmt.Sprintf("/api/v1/files/%s", url.PathEscape(id)), query, nil, nil, nil)
}

// CopyAFile: Copy a file (POST /api/v1/files/{id}/copy).
func (c *Client) CopyAFile(ctx context.Context, id string, body any) (*Response, error) {
	return c.do(ctx, "POST", fmt.Sprintf("/api/v1/files/%s/copy", url.PathEscape(id)), nil, body, nil, nil)
}

// DownloadAFile: Download a file (GET /api/v1/files/{id}/download).
func (c *Client) DownloadAFile(ctx context.Context, id string, query url.Values) (*Response, error) {
	return c.do(ctx, "GET", fmt.Sprintf("/api/v1/files/%s/download", url.PathEscape(id)), query, nil, nil, nil)
}

// GetFileMetadata: Get file metadata (GET /api/v1/files/{id}/metadata).
func (c *Client) GetFileMetadata(ctx context.Context, id string) (*Response, error) {
	return c.do(ctx, "GET", fmt.Sprintf("/api/v1/files/%s/metadata", url.PathEscape(id)), nil, nil, nil, nil)
}

// MoveAFile: Move a file (POST /api/v1/files/{id}/move).
func (c *Client) MoveAFile(ctx context.Context, id string, body any) (*Response, error) {
	return c.do(ctx, "POST", fmt.Sprintf("/api/v1/files/%s/move", url.PathEscape(id)), nil, body, nil, nil)
}

// ListFolders: List folders (GET /api/v1/folders).
func (c *Client) ListFolders(ctx context.Context, query url.Values) (*Response, error) {
	return c.do(ctx, "GET", "/api/v1/folders", query, nil, nil, nil)
}

// CreateAFolder: Create a folder (POST /api/v1/folders).
func (c *Client) CreateAFolder(ctx context.Context, body any) (*Response, error) {
	return c.do(ctx, "POST", "/api/v1/folders", nil, body, nil, nil)
}

// GetAFolder: Get a folder (GET /api/v1/folders/{id}).
func (c *Client) GetAFolder(ctx context.Context, id string) (*Response, error) {
	return c.do(ctx, "GET", fmt.Sprintf("/api/v1/folders/%s", url.PathEscape(id)), nil, nil, nil, nil)
}

// UpdateMoveAFolder: Update / move a folder (PATCH /api/v1/folders/{id}).
func (c *Client) UpdateMoveAFolder(ctx context.Context, id string, body any) (*Response, error) {
	return c.do(ctx, "PATCH", fmt.Sprintf("/api/v1/folders/%s", url.PathEscape(id)), nil, body, nil, nil)
}

// DeleteAFolder: Delete a folder (DELETE /api/v1/folders/{id}).
func (c *Client) DeleteAFolder(ctx context.Context, id string, query url.Values) (*Response, error) {
	return c.do(ctx, "DELETE", fmt.Sprintf("/api/v1/folders/%s", url.PathEscape(id)), query, nil, nil, nil)
}

// ListImageVariants: List image variants (GET /api/v1/files/{id}/variants).
func (c *Client) ListImageVariants(ctx context.Context, id string) (*Response, error) {
	return c.do(ctx, "GET", fmt.Sprintf("/api/v1/files/%s/variants", url.PathEscape(id)), nil, nil, nil, nil)
}

// DeleteCachedImageVariants: Delete cached image variants (DELETE /api/v1/files/{id}/variants).
func (c *Client) DeleteCachedImageVariants(ctx context.Context, id string) (*Response, error) {
	return c.do(ctx, "DELETE", fmt.Sprintf("/api/v1/files/%s/variants", url.PathEscape(id)), nil, nil, nil, nil)
}

// SignAnImageTransformationUrl: Sign an image transformation URL (POST /api/v1/images/sign).
func (c *Client) SignAnImageTransformationUrl(ctx context.Context, body any) (*Response, error) {
	return c.do(ctx, "POST", "/api/v1/images/sign", nil, body, nil, nil)
}

// ListMediaRenditions: List media renditions (GET /api/v1/files/{id}/media).
func (c *Client) ListMediaRenditions(ctx context.Context, id string, query url.Values) (*Response, error) {
	return c.do(ctx, "GET", fmt.Sprintf("/api/v1/files/%s/media", url.PathEscape(id)), query, nil, nil, nil)
}

// GenerateMediaRenditions: Generate media renditions (POST /api/v1/files/{id}/media/process).
func (c *Client) GenerateMediaRenditions(ctx context.Context, id string, body any) (*Response, error) {
	return c.do(ctx, "POST", fmt.Sprintf("/api/v1/files/%s/media/process", url.PathEscape(id)), nil, body, nil, nil)
}

// CreateAShareLink: Create a share link (POST /api/v1/files/{id}/shares).
func (c *Client) CreateAShareLink(ctx context.Context, id string, body any) (*Response, error) {
	return c.do(ctx, "POST", fmt.Sprintf("/api/v1/files/%s/shares", url.PathEscape(id)), nil, body, nil, nil)
}

// ListShareLinks: List share links (GET /api/v1/shares).
func (c *Client) ListShareLinks(ctx context.Context, query url.Values) (*Response, error) {
	return c.do(ctx, "GET", "/api/v1/shares", query, nil, nil, nil)
}

// GetAShareLinkWithItsAccessLog: Get a share link with its access log (GET /api/v1/shares/{id}).
func (c *Client) GetAShareLinkWithItsAccessLog(ctx context.Context, id string) (*Response, error) {
	return c.do(ctx, "GET", fmt.Sprintf("/api/v1/shares/%s", url.PathEscape(id)), nil, nil, nil, nil)
}

// UpdateAShareLink: Update a share link (PATCH /api/v1/shares/{id}).
func (c *Client) UpdateAShareLink(ctx context.Context, id string, body any) (*Response, error) {
	return c.do(ctx, "PATCH", fmt.Sprintf("/api/v1/shares/%s", url.PathEscape(id)), nil, body, nil, nil)
}

// RevokeAShareLink: Revoke a share link (POST /api/v1/shares/{id}/revoke).
func (c *Client) RevokeAShareLink(ctx context.Context, id string) (*Response, error) {
	return c.do(ctx, "POST", fmt.Sprintf("/api/v1/shares/%s/revoke", url.PathEscape(id)), nil, nil, nil, nil)
}

// CreateASignedUrl: Create a signed URL (POST /api/v1/files/{id}/signed-url).
func (c *Client) CreateASignedUrl(ctx context.Context, id string, body any) (*Response, error) {
	return c.do(ctx, "POST", fmt.Sprintf("/api/v1/files/%s/signed-url", url.PathEscape(id)), nil, body, nil, nil)
}

// UploadOneOrMoreFiles: Upload one or more files (POST /api/v1/uploads).
func (c *Client) UploadOneOrMoreFiles(ctx context.Context, form *Multipart) (*Response, error) {
	return c.do(ctx, "POST", "/api/v1/uploads", nil, nil, form, nil)
}

// GetUploadStatus: Get upload status (GET /api/v1/uploads/{id}).
func (c *Client) GetUploadStatus(ctx context.Context, id string) (*Response, error) {
	return c.do(ctx, "GET", fmt.Sprintf("/api/v1/uploads/%s", url.PathEscape(id)), nil, nil, nil, nil)
}

// AbortAChunkedUpload: Abort a chunked upload (DELETE /api/v1/uploads/{id}).
func (c *Client) AbortAChunkedUpload(ctx context.Context, id string) (*Response, error) {
	return c.do(ctx, "DELETE", fmt.Sprintf("/api/v1/uploads/%s", url.PathEscape(id)), nil, nil, nil, nil)
}

// UploadAChunk: Upload a chunk (POST /api/v1/uploads/{id}/chunk).
func (c *Client) UploadAChunk(ctx context.Context, id string, query url.Values, data []byte) (*Response, error) {
	return c.do(ctx, "POST", fmt.Sprintf("/api/v1/uploads/%s/chunk", url.PathEscape(id)), query, nil, nil, data)
}

// CompleteAChunkedUpload: Complete a chunked upload (POST /api/v1/uploads/{id}/complete).
func (c *Client) CompleteAChunkedUpload(ctx context.Context, id string) (*Response, error) {
	return c.do(ctx, "POST", fmt.Sprintf("/api/v1/uploads/%s/complete", url.PathEscape(id)), nil, nil, nil, nil)
}

// StartAChunkedResumableUpload: Start a chunked (resumable) upload (POST /api/v1/uploads/init).
func (c *Client) StartAChunkedResumableUpload(ctx context.Context, body any) (*Response, error) {
	return c.do(ctx, "POST", "/api/v1/uploads/init", nil, body, nil, nil)
}

// UsageForAScope: Usage for a scope (GET /api/v1/usage).
func (c *Client) UsageForAScope(ctx context.Context, query url.Values) (*Response, error) {
	return c.do(ctx, "GET", "/api/v1/usage", query, nil, nil, nil)
}

// RestoreAFileFromTheRecycleBin: Restore a file from the recycle bin (POST /api/v1/files/{id}/restore).
func (c *Client) RestoreAFileFromTheRecycleBin(ctx context.Context, id string, body any) (*Response, error) {
	return c.do(ctx, "POST", fmt.Sprintf("/api/v1/files/%s/restore", url.PathEscape(id)), nil, body, nil, nil)
}

// ListFileRevisions: List file revisions (GET /api/v1/files/{id}/versions).
func (c *Client) ListFileRevisions(ctx context.Context, id string) (*Response, error) {
	return c.do(ctx, "GET", fmt.Sprintf("/api/v1/files/%s/versions", url.PathEscape(id)), nil, nil, nil, nil)
}

// UploadANewRevision: Upload a new revision (POST /api/v1/files/{id}/versions).
func (c *Client) UploadANewRevision(ctx context.Context, id string, form *Multipart) (*Response, error) {
	return c.do(ctx, "POST", fmt.Sprintf("/api/v1/files/%s/versions", url.PathEscape(id)), nil, nil, form, nil)
}

// DeleteARevision: Delete a revision (DELETE /api/v1/files/{id}/versions/{version}).
func (c *Client) DeleteARevision(ctx context.Context, id string, version string) (*Response, error) {
	return c.do(ctx, "DELETE", fmt.Sprintf("/api/v1/files/%s/versions/%s", url.PathEscape(id), url.PathEscape(version)), nil, nil, nil, nil)
}

// RollBackToARevision: Roll back to a revision (POST /api/v1/files/{id}/versions/{version}/restore).
func (c *Client) RollBackToARevision(ctx context.Context, id string, version string) (*Response, error) {
	return c.do(ctx, "POST", fmt.Sprintf("/api/v1/files/%s/versions/%s/restore", url.PathEscape(id), url.PathEscape(version)), nil, nil, nil, nil)
}

// ListTheRecycleBin: List the recycle bin (GET /api/v1/trash).
func (c *Client) ListTheRecycleBin(ctx context.Context, query url.Values) (*Response, error) {
	return c.do(ctx, "GET", "/api/v1/trash", query, nil, nil, nil)
}

// PermanentlyDeleteAFileFromTheRecycleBin: Permanently delete a file from the recycle bin (DELETE /api/v1/trash/{id}).
func (c *Client) PermanentlyDeleteAFileFromTheRecycleBin(ctx context.Context, id string) (*Response, error) {
	return c.do(ctx, "DELETE", fmt.Sprintf("/api/v1/trash/%s", url.PathEscape(id)), nil, nil, nil, nil)
}

// MakeADomainPrimary: Make a domain primary (PATCH /api/v1/domains/{id}).
func (c *Client) MakeADomainPrimary(ctx context.Context, id string, body any) (*Response, error) {
	return c.do(ctx, "PATCH", fmt.Sprintf("/api/v1/domains/%s", url.PathEscape(id)), nil, body, nil, nil)
}

// RemoveADomain: Remove a domain (DELETE /api/v1/domains/{id}).
func (c *Client) RemoveADomain(ctx context.Context, id string) (*Response, error) {
	return c.do(ctx, "DELETE", fmt.Sprintf("/api/v1/domains/%s", url.PathEscape(id)), nil, nil, nil, nil)
}

// RunADomainHealthCheck: Run a domain health check (POST /api/v1/domains/{id}/check).
func (c *Client) RunADomainHealthCheck(ctx context.Context, id string) (*Response, error) {
	return c.do(ctx, "POST", fmt.Sprintf("/api/v1/domains/%s/check", url.PathEscape(id)), nil, nil, nil, nil)
}

// VerifyADomain: Verify a domain (POST /api/v1/domains/{id}/verify).
func (c *Client) VerifyADomain(ctx context.Context, id string) (*Response, error) {
	return c.do(ctx, "POST", fmt.Sprintf("/api/v1/domains/%s/verify", url.PathEscape(id)), nil, nil, nil, nil)
}

// ListProjects: List projects (GET /api/v1/projects).
func (c *Client) ListProjects(ctx context.Context) (*Response, error) {
	return c.do(ctx, "GET", "/api/v1/projects", nil, nil, nil, nil)
}

// ListZones: List zones (GET /api/v1/zones).
func (c *Client) ListZones(ctx context.Context, query url.Values) (*Response, error) {
	return c.do(ctx, "GET", "/api/v1/zones", query, nil, nil, nil)
}

// CreateAZone: Create a zone (POST /api/v1/zones).
func (c *Client) CreateAZone(ctx context.Context, body any) (*Response, error) {
	return c.do(ctx, "POST", "/api/v1/zones", nil, body, nil, nil)
}

// GetAZone: Get a zone (GET /api/v1/zones/{id}).
func (c *Client) GetAZone(ctx context.Context, id string) (*Response, error) {
	return c.do(ctx, "GET", fmt.Sprintf("/api/v1/zones/%s", url.PathEscape(id)), nil, nil, nil, nil)
}

// UpdateAZone: Update a zone (PATCH /api/v1/zones/{id}).
func (c *Client) UpdateAZone(ctx context.Context, id string, body any) (*Response, error) {
	return c.do(ctx, "PATCH", fmt.Sprintf("/api/v1/zones/%s", url.PathEscape(id)), nil, body, nil, nil)
}

// AddACustomDomain: Add a custom domain (POST /api/v1/zones/{id}/domains).
func (c *Client) AddACustomDomain(ctx context.Context, id string, body any) (*Response, error) {
	return c.do(ctx, "POST", fmt.Sprintf("/api/v1/zones/%s/domains", url.PathEscape(id)), nil, body, nil, nil)
}

// ReplicationStatus: Replication status (GET /api/v1/zones/{id}/replication).
func (c *Client) ReplicationStatus(ctx context.Context, id string) (*Response, error) {
	return c.do(ctx, "GET", fmt.Sprintf("/api/v1/zones/%s/replication", url.PathEscape(id)), nil, nil, nil, nil)
}
