// Code generated by scripts/generate-sdks.mjs from the OpenAPI document. DO NOT EDIT.
import { CdnCore, type RequestOptions } from './core.js';

/** CDNPanel API client. Every method maps to one REST endpoint. */
export class CdnClient extends CdnCore {
  /**
   * Identify the caller — Returns the authenticated principal: for API keys the key metadata and granted scopes; for staff sessions the user, roles and permissions. Useful for verifying a key works.
   * `GET /api/v1/me`
   */
  identifyTheCaller<T = any>(options: { signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/me`, { method: 'GET', signal: options.signal } as RequestOptions);
  }

  /**
   * Analytics overview — Totals, a time series (hourly for ≤ 3 days, otherwise daily) and breakdowns by status code, country, MIME type, file, folder and API key, plus recent errors. Use `period` or `period=custom` with `from`/`to`.
   * `GET /api/v1/analytics` · scopes: analytics:read
   */
  analyticsOverview<T = any>(options: { query?: { "period"?: string | number | boolean; "from"?: string | number | boolean; "to"?: string | number | boolean; "api_key_id"?: string | number | boolean }; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/analytics`, { method: 'GET', signal: options.signal, query: options.query } as RequestOptions);
  }

  /**
   * Bandwidth usage — Bandwidth served today, this month (UTC) and as a time series for the selected period.
   * `GET /api/v1/analytics/bandwidth` · scopes: analytics:read
   */
  bandwidthUsage<T = any>(options: { query?: { "period"?: string | number | boolean; "from"?: string | number | boolean; "to"?: string | number | boolean }; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/analytics/bandwidth`, { method: 'GET', signal: options.signal, query: options.query } as RequestOptions);
  }

  /**
   * Analytics for a file
   * `GET /api/v1/analytics/files/{id}` · scopes: analytics:read
   */
  analyticsForAFile<T = any>(id: string, options: { query?: { "period"?: string | number | boolean; "from"?: string | number | boolean; "to"?: string | number | boolean }; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/analytics/files/${encodeURIComponent(id)}`, { method: 'GET', signal: options.signal, query: options.query } as RequestOptions);
  }

  /**
   * Global delivery map data — Requests, bandwidth and origin cache-hit ratio per visitor country, plus flows from storage origins (by provider region / served countries) to countries.
   * `GET /api/v1/analytics/geo` · scopes: analytics:read
   */
  globalDeliveryMapData<T = any>(options: { query?: { "period"?: string | number | boolean; "zone_id"?: string | number | boolean }; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/analytics/geo`, { method: 'GET', signal: options.signal, query: options.query } as RequestOptions);
  }

  /**
   * Update a cache rule
   * `PATCH /api/v1/cache-rules/{id}` · scopes: zones:write
   */
  updateACacheRule<T = any>(id: string, options: { body?: Record<string, unknown>; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/cache-rules/${encodeURIComponent(id)}`, { method: 'PATCH', signal: options.signal, body: options.body } as RequestOptions);
  }

  /**
   * Delete a cache rule
   * `DELETE /api/v1/cache-rules/{id}` · scopes: zones:write
   */
  deleteACacheRule<T = any>(id: string, options: { signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/cache-rules/${encodeURIComponent(id)}`, { method: 'DELETE', signal: options.signal } as RequestOptions);
  }

  /**
   * Pre-warm the edge cache — Fetches public URLs through the edge so they are cached before visitors request them. Pass explicit `urls`, `file_ids`, or `top` to warm the most-requested public files of the last 7 days.
   * `POST /api/v1/cache/prewarm` · scopes: cache:purge
   */
  preWarmTheEdgeCache<T = any>(options: { body?: Record<string, unknown>; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/cache/prewarm`, { method: 'POST', signal: options.signal, body: options.body } as RequestOptions);
  }

  /**
   * Purge the CDN cache — Purges edge caches by `url`, `file` (file ids — all URLs, signed URLs and image variants), `folder` (folder ids — everything beneath), `tag` (cache tags), `zone` (zone ids) or `everything`. Purges run asynchronously through the Cloudflare API when credentials are configured; otherwise they are recorded as `origin_only`.
   * `POST /api/v1/cache/purge` · scopes: cache:purge
   */
  purgeTheCdnCache<T = any>(options: { body?: Record<string, unknown>; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/cache/purge`, { method: 'POST', signal: options.signal, body: options.body } as RequestOptions);
  }

  /**
   * Purge history
   * `GET /api/v1/cache/purges` · scopes: cache:purge
   */
  purgeHistory<T = any>(options: { query?: { "page"?: string | number | boolean; "limit"?: string | number | boolean; "zone_id"?: string | number | boolean }; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/cache/purges`, { method: 'GET', signal: options.signal, query: options.query } as RequestOptions);
  }

  /**
   * Cache statistics — Origin-side cache statistics (revalidations, ranges, redirects, image-variant hits/misses) from request logs, plus the edge HIT / MISS / EXPIRED / BYPASS breakdown from Cloudflare analytics when credentials are configured.
   * `GET /api/v1/cache/stats` · scopes: analytics:read
   */
  cacheStatistics<T = any>(options: { query?: { "zone_id"?: string | number | boolean; "period"?: string | number | boolean }; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/cache/stats`, { method: 'GET', signal: options.signal, query: options.query } as RequestOptions);
  }

  /**
   * Explain a file’s cache policy — Shows the zone, matching cache rule, edge/browser TTLs, cache tags and the URLs that a purge of this file covers.
   * `GET /api/v1/files/{id}/cache` · scopes: files:read
   */
  explainAFilesCachePolicy<T = any>(id: string, options: { signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/files/${encodeURIComponent(id)}/cache`, { method: 'GET', signal: options.signal } as RequestOptions);
  }

  /**
   * Create a cache rule — Cache rules override zone TTLs for matching paths (zone-relative globs: `*` within a segment, `**` across segments; a pattern without "/" matches the file name, e.g. `*.css`). The first matching rule by priority wins. `bypass` disables edge caching.
   * `POST /api/v1/zones/{id}/cache-rules` · scopes: zones:write
   */
  createACacheRule<T = any>(id: string, options: { body?: Record<string, unknown>; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/zones/${encodeURIComponent(id)}/cache-rules`, { method: 'POST', signal: options.signal, body: options.body } as RequestOptions);
  }

  /**
   * Issue a signed access cookie — Grants time-limited access to every private / authenticated file below a folder ("protected collection") without signing each URL. Returns the cookie value and an `install_url` on the CDN host that sets the cookie (HttpOnly, Secure) and redirects — send visitors there once, then plain URLs work.
   * `POST /api/v1/signed-cookies` · scopes: files:read
   */
  issueASignedAccessCookie<T = any>(options: { body?: Record<string, unknown>; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/signed-cookies`, { method: 'POST', signal: options.signal, body: options.body } as RequestOptions);
  }

  /**
   * List and search files — Returns a paginated list of files. Supports search by name / id / checksum and filtering by folder, type, MIME, visibility, uploader, date and size.
   * `GET /api/v1/files` · scopes: files:read
   */
  listAndSearchFiles<T = any>(options: { query?: { "page"?: string | number | boolean; "limit"?: string | number | boolean; "folder_id"?: string | number | boolean; "recursive"?: string | number | boolean; "q"?: string | number | boolean; "mime"?: string | number | boolean; "type"?: string | number | boolean; "visibility"?: string | number | boolean; "status"?: string | number | boolean; "tag"?: string | number | boolean; "uploaded_by"?: string | number | boolean; "created_after"?: string | number | boolean; "created_before"?: string | number | boolean; "min_size"?: string | number | boolean; "max_size"?: string | number | boolean; "sort"?: string | number | boolean; "order"?: string | number | boolean }; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/files`, { method: 'GET', signal: options.signal, query: options.query } as RequestOptions);
  }

  /**
   * Upload a file — Uploads a single file using `multipart/form-data`. Options may be sent as form fields **before** the `file` part, or as query parameters. The real content type is detected from the file contents; the file name, extension and browser `Content-Type` are not trusted. For files larger than ~100 MB prefer the chunked upload API.
   * `POST /api/v1/files` · scopes: files:upload
   */
  uploadAFile<T = any>(options: { form: FormData; signal?: AbortSignal }): Promise<T> {
    return this.request<T>(`/api/v1/files`, { method: 'POST', signal: options.signal, form: options.form } as RequestOptions);
  }

  /**
   * Get a file
   * `GET /api/v1/files/{id}` · scopes: files:read
   */
  getAFile<T = any>(id: string, options: { signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/files/${encodeURIComponent(id)}`, { method: 'GET', signal: options.signal } as RequestOptions);
  }

  /**
   * Update a file — Renames a file or changes its visibility, cache settings, download behaviour or custom metadata. Changing `metadata` with an API key requires the `metadata:write` scope.
   * `PATCH /api/v1/files/{id}` · scopes: files:update
   */
  updateAFile<T = any>(id: string, options: { body?: Record<string, unknown>; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/files/${encodeURIComponent(id)}`, { method: 'PATCH', signal: options.signal, body: options.body } as RequestOptions);
  }

  /**
   * Delete a file — Moves the file to the recycle bin (restorable for the configured retention period; it stops being served immediately). Pass `permanent=true` to delete the record and, once nothing else references it, the stored object right away.
   * `DELETE /api/v1/files/{id}` · scopes: files:delete
   */
  deleteAFile<T = any>(id: string, options: { query?: { "permanent"?: string | number | boolean }; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/files/${encodeURIComponent(id)}`, { method: 'DELETE', signal: options.signal, query: options.query } as RequestOptions);
  }

  /**
   * Copy a file — Creates a new file record with the same content. File content is immutable, so the stored object is shared.
   * `POST /api/v1/files/{id}/copy` · scopes: files:update, files:upload
   */
  copyAFile<T = any>(id: string, options: { body?: Record<string, unknown>; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/files/${encodeURIComponent(id)}/copy`, { method: 'POST', signal: options.signal, body: options.body } as RequestOptions);
  }

  /**
   * Download a file — Downloads the file content regardless of its visibility (authorised callers only). Supports `Range`, `If-None-Match` and `If-Modified-Since`. Responses are always `Cache-Control: private`.
   * `GET /api/v1/files/{id}/download` · scopes: files:read
   */
  downloadAFile<T = Response>(id: string, options: { query?: { "disposition"?: string | number | boolean }; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/files/${encodeURIComponent(id)}/download`, { method: 'GET', signal: options.signal, query: options.query, responseType: 'response' } as RequestOptions);
  }

  /**
   * Get file metadata — Technical metadata (type, size, checksum, dimensions, duration, scan state) plus custom metadata.
   * `GET /api/v1/files/{id}/metadata` · scopes: metadata:read
   */
  getFileMetadata<T = any>(id: string, options: { signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/files/${encodeURIComponent(id)}/metadata`, { method: 'GET', signal: options.signal } as RequestOptions);
  }

  /**
   * Move a file
   * `POST /api/v1/files/{id}/move` · scopes: files:update
   */
  moveAFile<T = any>(id: string, options: { body?: Record<string, unknown>; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/files/${encodeURIComponent(id)}/move`, { method: 'POST', signal: options.signal, body: options.body } as RequestOptions);
  }

  /**
   * List folders — Lists the direct children of `parent_id` ("root" by default). Pass `all=true` to get every accessible folder (flat, ordered by path).
   * `GET /api/v1/folders` · scopes: folders:read
   */
  listFolders<T = any>(options: { query?: { "page"?: string | number | boolean; "limit"?: string | number | boolean; "parent_id"?: string | number | boolean; "q"?: string | number | boolean; "all"?: string | number | boolean }; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/folders`, { method: 'GET', signal: options.signal, query: options.query } as RequestOptions);
  }

  /**
   * Create a folder
   * `POST /api/v1/folders` · scopes: folders:write
   */
  createAFolder<T = any>(options: { body?: Record<string, unknown>; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/folders`, { method: 'POST', signal: options.signal, body: options.body } as RequestOptions);
  }

  /**
   * Get a folder — Returns the folder with file/sub-folder counts and its breadcrumb chain.
   * `GET /api/v1/folders/{id}` · scopes: folders:read
   */
  getAFolder<T = any>(id: string, options: { signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/folders/${encodeURIComponent(id)}`, { method: 'GET', signal: options.signal } as RequestOptions);
  }

  /**
   * Update / move a folder — Renames a folder, moves it under another parent (`parent_id`, or null for the top level), or changes its default visibility and role restrictions. Friendly paths of all descendants are updated.
   * `PATCH /api/v1/folders/{id}` · scopes: folders:write
   */
  updateMoveAFolder<T = any>(id: string, options: { body?: Record<string, unknown>; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/folders/${encodeURIComponent(id)}`, { method: 'PATCH', signal: options.signal, body: options.body } as RequestOptions);
  }

  /**
   * Delete a folder — Deletes an empty folder. With `recursive=true` all sub-folders and files are deleted too (requires `files.delete` / `files:delete`, and for staff a recent password re-authentication).
   * `DELETE /api/v1/folders/{id}` · scopes: folders:write
   */
  deleteAFolder<T = any>(id: string, options: { query?: { "recursive"?: string | number | boolean }; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/folders/${encodeURIComponent(id)}`, { method: 'DELETE', signal: options.signal, query: options.query } as RequestOptions);
  }

  /**
   * List image variants
   * `GET /api/v1/files/{id}/variants` · scopes: files:read
   */
  listImageVariants<T = any>(id: string, options: { signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/files/${encodeURIComponent(id)}/variants`, { method: 'GET', signal: options.signal } as RequestOptions);
  }

  /**
   * Delete cached image variants — Removes stored variants (they are regenerated on demand) and purges the file from edge caches.
   * `DELETE /api/v1/files/{id}/variants` · scopes: files:update
   */
  deleteCachedImageVariants<T = any>(id: string, options: { signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/files/${encodeURIComponent(id)}/variants`, { method: 'DELETE', signal: options.signal } as RequestOptions);
  }

  /**
   * Sign an image transformation URL — Validates the parameters and returns a signed `/img/` URL (on the zone primary domain when the file belongs to a zone with an active domain).
   * `POST /api/v1/images/sign` · scopes: files:read
   */
  signAnImageTransformationUrl<T = any>(options: { body?: Record<string, unknown>; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/images/sign`, { method: 'POST', signal: options.signal, body: options.body } as RequestOptions);
  }

  /**
   * List media renditions — Returns renditions with playable URLs. URLs of non-public files carry a media token valid for `ttl` seconds (default 4 hours).
   * `GET /api/v1/files/{id}/media` · scopes: files:read
   */
  listMediaRenditions<T = any>(id: string, options: { query?: { "ttl"?: string | number | boolean }; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/files/${encodeURIComponent(id)}/media`, { method: 'GET', signal: options.signal, query: options.query } as RequestOptions);
  }

  /**
   * Generate media renditions — Queues rendition generation (FFmpeg) for a video or audio file. Defaults to the renditions configured in settings.
   * `POST /api/v1/files/{id}/media/process` · scopes: files:update
   */
  generateMediaRenditions<T = any>(id: string, options: { body?: Record<string, unknown>; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/files/${encodeURIComponent(id)}/media/process`, { method: 'POST', signal: options.signal, body: options.body } as RequestOptions);
  }

  /**
   * Create a share link — Creates a human-friendly share URL for a file — works for private files without handing out API keys. Optional password, expiry, download limit, one-time use, IP / country restrictions and email capture. The URL (with its secret token) is only returned once.
   * `POST /api/v1/files/{id}/shares` · scopes: shares:write
   */
  createAShareLink<T = any>(id: string, options: { body?: Record<string, unknown>; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/files/${encodeURIComponent(id)}/shares`, { method: 'POST', signal: options.signal, body: options.body } as RequestOptions);
  }

  /**
   * List share links
   * `GET /api/v1/shares` · scopes: shares:write
   */
  listShareLinks<T = any>(options: { query?: { "page"?: string | number | boolean; "limit"?: string | number | boolean; "file_id"?: string | number | boolean; "state"?: string | number | boolean }; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/shares`, { method: 'GET', signal: options.signal, query: options.query } as RequestOptions);
  }

  /**
   * Get a share link with its access log
   * `GET /api/v1/shares/{id}` · scopes: shares:write
   */
  getAShareLinkWithItsAccessLog<T = any>(id: string, options: { signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/shares/${encodeURIComponent(id)}`, { method: 'GET', signal: options.signal } as RequestOptions);
  }

  /**
   * Update a share link — Changes limits and restrictions. Pass `password: null` to remove the password.
   * `PATCH /api/v1/shares/{id}` · scopes: shares:write
   */
  updateAShareLink<T = any>(id: string, options: { body?: Record<string, unknown>; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/shares/${encodeURIComponent(id)}`, { method: 'PATCH', signal: options.signal, body: options.body } as RequestOptions);
  }

  /**
   * Revoke a share link
   * `POST /api/v1/shares/{id}/revoke` · scopes: shares:write
   */
  revokeAShareLink<T = any>(id: string, options: { signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/shares/${encodeURIComponent(id)}/revoke`, { method: 'POST', signal: options.signal } as RequestOptions);
  }

  /**
   * Create a signed URL — Returns a time-limited URL that grants read access to the file without other credentials. The URL is signed with HMAC-SHA256; altering the file id, expiry or disposition invalidates it.
   * `POST /api/v1/files/{id}/signed-url` · scopes: files:read
   */
  createASignedUrl<T = any>(id: string, options: { body?: Record<string, unknown>; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/files/${encodeURIComponent(id)}/signed-url`, { method: 'POST', signal: options.signal, body: options.body } as RequestOptions);
  }

  /**
   * Upload one or more files — Multipart upload of up to 20 files in one request (each part named `file`). Options apply to all files and must be sent before the file parts (or as query parameters). Each file succeeds or fails independently.
   * `POST /api/v1/uploads` · scopes: files:upload
   */
  uploadOneOrMoreFiles<T = any>(options: { form: FormData; signal?: AbortSignal }): Promise<T> {
    return this.request<T>(`/api/v1/uploads`, { method: 'POST', signal: options.signal, form: options.form } as RequestOptions);
  }

  /**
   * Get upload status — Returns the upload session including which chunks have been received — use it to resume an interrupted upload.
   * `GET /api/v1/uploads/{id}` · scopes: files:upload
   */
  getUploadStatus<T = any>(id: string, options: { signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/uploads/${encodeURIComponent(id)}`, { method: 'GET', signal: options.signal } as RequestOptions);
  }

  /**
   * Abort a chunked upload
   * `DELETE /api/v1/uploads/{id}` · scopes: files:upload
   */
  abortAChunkedUpload<T = any>(id: string, options: { signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/uploads/${encodeURIComponent(id)}`, { method: 'DELETE', signal: options.signal } as RequestOptions);
  }

  /**
   * Upload a chunk — Request body is the raw chunk bytes with `Content-Type: application/octet-stream`. Re-sending an already received chunk overwrites it.
   * `POST /api/v1/uploads/{id}/chunk` · scopes: files:upload
   */
  uploadAChunk<T = any>(id: string, options: { query?: { "index"?: string | number | boolean }; data: Uint8Array | Blob; signal?: AbortSignal }): Promise<T> {
    return this.request<T>(`/api/v1/uploads/${encodeURIComponent(id)}/chunk`, { method: 'POST', signal: options.signal, query: options.query, raw: options.data } as RequestOptions);
  }

  /**
   * Complete a chunked upload — Assembles the chunks, verifies size and checksum, validates the content and creates the file.
   * `POST /api/v1/uploads/{id}/complete` · scopes: files:upload
   */
  completeAChunkedUpload<T = any>(id: string, options: { signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/uploads/${encodeURIComponent(id)}/complete`, { method: 'POST', signal: options.signal } as RequestOptions);
  }

  /**
   * Start a chunked (resumable) upload — Creates an upload session for large files. Send each chunk with `POST /api/v1/uploads/{id}/chunk?index=N` (raw bytes, `Content-Type: application/octet-stream`); every chunk except the last must be exactly `chunk_size` bytes. Chunks can be sent in any order and retried. Finish with `POST /api/v1/uploads/{id}/complete`.
   * `POST /api/v1/uploads/init` · scopes: files:upload
   */
  startAChunkedResumableUpload<T = any>(options: { body?: Record<string, unknown>; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/uploads/init`, { method: 'POST', signal: options.signal, body: options.body } as RequestOptions);
  }

  /**
   * Usage for a scope — Month-to-date usage (UTC) for the platform, a project, a zone or an API key: storage, egress, requests, image transformations, uploads and transformation CPU time, with quotas and a cost estimate based on each storage provider’s configured prices.
   * `GET /api/v1/usage` · scopes: usage:read
   */
  usageForAScope<T = any>(options: { query?: { "scope_type"?: string | number | boolean; "scope_id"?: string | number | boolean }; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/usage`, { method: 'GET', signal: options.signal, query: options.query } as RequestOptions);
  }

  /**
   * Restore a file from the recycle bin — Restores the file into its original folder (or `folder_id`). If the original folder no longer exists the file is restored to the top level.
   * `POST /api/v1/files/{id}/restore` · scopes: files:delete
   */
  restoreAFileFromTheRecycleBin<T = any>(id: string, options: { body?: Record<string, unknown>; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/files/${encodeURIComponent(id)}/restore`, { method: 'POST', signal: options.signal, body: options.body } as RequestOptions);
  }

  /**
   * List file revisions — Previous revisions of a file, newest first. The current revision is the file itself (`version` field).
   * `GET /api/v1/files/{id}/versions` · scopes: files:read
   */
  listFileRevisions<T = any>(id: string, options: { signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/files/${encodeURIComponent(id)}/versions`, { method: 'GET', signal: options.signal } as RequestOptions);
  }

  /**
   * Upload a new revision — Replaces the content of a file while keeping its id, URLs and settings (`multipart/form-data`, field `file`). The previous content is kept as a revision; derived variants are regenerated and edge caches are purged.
   * `POST /api/v1/files/{id}/versions` · scopes: files:update, files:upload
   */
  uploadANewRevision<T = any>(id: string, options: { form: FormData; signal?: AbortSignal }): Promise<T> {
    return this.request<T>(`/api/v1/files/${encodeURIComponent(id)}/versions`, { method: 'POST', signal: options.signal, form: options.form } as RequestOptions);
  }

  /**
   * Delete a revision
   * `DELETE /api/v1/files/{id}/versions/{version}` · scopes: files:delete
   */
  deleteARevision<T = any>(id: string, version: string, options: { signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/files/${encodeURIComponent(id)}/versions/${encodeURIComponent(version)}`, { method: 'DELETE', signal: options.signal } as RequestOptions);
  }

  /**
   * Roll back to a revision — Makes an earlier revision current again. The content that was current becomes a new revision, so a rollback can itself be undone.
   * `POST /api/v1/files/{id}/versions/{version}/restore` · scopes: files:update
   */
  rollBackToARevision<T = any>(id: string, version: string, options: { signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/files/${encodeURIComponent(id)}/versions/${encodeURIComponent(version)}/restore`, { method: 'POST', signal: options.signal } as RequestOptions);
  }

  /**
   * List the recycle bin — Deleted files kept for the configured retention period (Settings → Files). Restore them with `POST /api/v1/files/{id}/restore`.
   * `GET /api/v1/trash` · scopes: files:read
   */
  listTheRecycleBin<T = any>(options: { query?: { "page"?: string | number | boolean; "limit"?: string | number | boolean; "q"?: string | number | boolean }; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/trash`, { method: 'GET', signal: options.signal, query: options.query } as RequestOptions);
  }

  /**
   * Permanently delete a file from the recycle bin
   * `DELETE /api/v1/trash/{id}` · scopes: files:delete
   */
  permanentlyDeleteAFileFromTheRecycleBin<T = any>(id: string, options: { signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/trash/${encodeURIComponent(id)}`, { method: 'DELETE', signal: options.signal } as RequestOptions);
  }

  /**
   * Make a domain primary — The primary domain is used when generating zone URLs.
   * `PATCH /api/v1/domains/{id}` · scopes: zones:write
   */
  makeADomainPrimary<T = any>(id: string, options: { body?: Record<string, unknown>; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/domains/${encodeURIComponent(id)}`, { method: 'PATCH', signal: options.signal, body: options.body } as RequestOptions);
  }

  /**
   * Remove a domain
   * `DELETE /api/v1/domains/{id}` · scopes: zones:write
   */
  removeADomain<T = any>(id: string, options: { signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/domains/${encodeURIComponent(id)}`, { method: 'DELETE', signal: options.signal } as RequestOptions);
  }

  /**
   * Run a domain health check
   * `POST /api/v1/domains/{id}/check` · scopes: zones:read
   */
  runADomainHealthCheck<T = any>(id: string, options: { signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/domains/${encodeURIComponent(id)}/check`, { method: 'POST', signal: options.signal } as RequestOptions);
  }

  /**
   * Verify a domain — Checks the TXT ownership record and, once verified, probes HTTPS reachability through the edge (TLS + routing).
   * `POST /api/v1/domains/{id}/verify` · scopes: zones:write
   */
  verifyADomain<T = any>(id: string, options: { signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/domains/${encodeURIComponent(id)}/verify`, { method: 'POST', signal: options.signal } as RequestOptions);
  }

  /**
   * List projects
   * `GET /api/v1/projects` · scopes: zones:read
   */
  listProjects<T = any>(options: { signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/projects`, { method: 'GET', signal: options.signal } as RequestOptions);
  }

  /**
   * List zones
   * `GET /api/v1/zones` · scopes: zones:read
   */
  listZones<T = any>(options: { query?: { "project_id"?: string | number | boolean }; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/zones`, { method: 'GET', signal: options.signal, query: options.query } as RequestOptions);
  }

  /**
   * Create a zone — Creates a CDN zone bound to a folder subtree. Pass `root_folder_id` to use an existing folder, or omit it to create a new top-level folder named after the zone. Every file in that subtree is delivered with the zone configuration.
   * `POST /api/v1/zones` · scopes: zones:write
   */
  createAZone<T = any>(options: { body?: Record<string, unknown>; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/zones`, { method: 'POST', signal: options.signal, body: options.body } as RequestOptions);
  }

  /**
   * Get a zone
   * `GET /api/v1/zones/{id}` · scopes: zones:read
   */
  getAZone<T = any>(id: string, options: { signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/zones/${encodeURIComponent(id)}`, { method: 'GET', signal: options.signal } as RequestOptions);
  }

  /**
   * Update a zone — Changes delivery configuration: TTLs, upload rules, image/video processing, hotlink and geo protection, replication strategy and replica providers.
   * `PATCH /api/v1/zones/{id}` · scopes: zones:write
   */
  updateAZone<T = any>(id: string, options: { body?: Record<string, unknown>; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/zones/${encodeURIComponent(id)}`, { method: 'PATCH', signal: options.signal, body: options.body } as RequestOptions);
  }

  /**
   * Add a custom domain — Adds a hostname to the zone. The response contains the DNS records to create: a TXT record proving ownership and a CNAME (or Cloudflare Tunnel public hostname) routing traffic here. Then call `POST /api/v1/domains/{id}/verify` (verification is also retried automatically).
   * `POST /api/v1/zones/{id}/domains` · scopes: zones:write
   */
  addACustomDomain<T = any>(id: string, options: { body?: Record<string, unknown>; signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/zones/${encodeURIComponent(id)}/domains`, { method: 'POST', signal: options.signal, body: options.body } as RequestOptions);
  }

  /**
   * Replication status
   * `GET /api/v1/zones/{id}/replication` · scopes: zones:read
   */
  replicationStatus<T = any>(id: string, options: { signal?: AbortSignal } = {}): Promise<T> {
    return this.request<T>(`/api/v1/zones/${encodeURIComponent(id)}/replication`, { method: 'GET', signal: options.signal } as RequestOptions);
  }

}

export const OPERATIONS = [
  {
    "name": "identifyTheCaller",
    "method": "GET",
    "path": "/api/v1/me",
    "tag": "Account"
  },
  {
    "name": "analyticsOverview",
    "method": "GET",
    "path": "/api/v1/analytics",
    "tag": "Analytics"
  },
  {
    "name": "bandwidthUsage",
    "method": "GET",
    "path": "/api/v1/analytics/bandwidth",
    "tag": "Analytics"
  },
  {
    "name": "analyticsForAFile",
    "method": "GET",
    "path": "/api/v1/analytics/files/{id}",
    "tag": "Analytics"
  },
  {
    "name": "globalDeliveryMapData",
    "method": "GET",
    "path": "/api/v1/analytics/geo",
    "tag": "Analytics"
  },
  {
    "name": "updateACacheRule",
    "method": "PATCH",
    "path": "/api/v1/cache-rules/{id}",
    "tag": "Cache"
  },
  {
    "name": "deleteACacheRule",
    "method": "DELETE",
    "path": "/api/v1/cache-rules/{id}",
    "tag": "Cache"
  },
  {
    "name": "preWarmTheEdgeCache",
    "method": "POST",
    "path": "/api/v1/cache/prewarm",
    "tag": "Cache"
  },
  {
    "name": "purgeTheCdnCache",
    "method": "POST",
    "path": "/api/v1/cache/purge",
    "tag": "Cache"
  },
  {
    "name": "purgeHistory",
    "method": "GET",
    "path": "/api/v1/cache/purges",
    "tag": "Cache"
  },
  {
    "name": "cacheStatistics",
    "method": "GET",
    "path": "/api/v1/cache/stats",
    "tag": "Cache"
  },
  {
    "name": "explainAFilesCachePolicy",
    "method": "GET",
    "path": "/api/v1/files/{id}/cache",
    "tag": "Cache"
  },
  {
    "name": "createACacheRule",
    "method": "POST",
    "path": "/api/v1/zones/{id}/cache-rules",
    "tag": "Cache"
  },
  {
    "name": "issueASignedAccessCookie",
    "method": "POST",
    "path": "/api/v1/signed-cookies",
    "tag": "Edge Security"
  },
  {
    "name": "listAndSearchFiles",
    "method": "GET",
    "path": "/api/v1/files",
    "tag": "Files"
  },
  {
    "name": "uploadAFile",
    "method": "POST",
    "path": "/api/v1/files",
    "tag": "Files"
  },
  {
    "name": "getAFile",
    "method": "GET",
    "path": "/api/v1/files/{id}",
    "tag": "Files"
  },
  {
    "name": "updateAFile",
    "method": "PATCH",
    "path": "/api/v1/files/{id}",
    "tag": "Files"
  },
  {
    "name": "deleteAFile",
    "method": "DELETE",
    "path": "/api/v1/files/{id}",
    "tag": "Files"
  },
  {
    "name": "copyAFile",
    "method": "POST",
    "path": "/api/v1/files/{id}/copy",
    "tag": "Files"
  },
  {
    "name": "downloadAFile",
    "method": "GET",
    "path": "/api/v1/files/{id}/download",
    "tag": "Files"
  },
  {
    "name": "getFileMetadata",
    "method": "GET",
    "path": "/api/v1/files/{id}/metadata",
    "tag": "Files"
  },
  {
    "name": "moveAFile",
    "method": "POST",
    "path": "/api/v1/files/{id}/move",
    "tag": "Files"
  },
  {
    "name": "listFolders",
    "method": "GET",
    "path": "/api/v1/folders",
    "tag": "Folders"
  },
  {
    "name": "createAFolder",
    "method": "POST",
    "path": "/api/v1/folders",
    "tag": "Folders"
  },
  {
    "name": "getAFolder",
    "method": "GET",
    "path": "/api/v1/folders/{id}",
    "tag": "Folders"
  },
  {
    "name": "updateMoveAFolder",
    "method": "PATCH",
    "path": "/api/v1/folders/{id}",
    "tag": "Folders"
  },
  {
    "name": "deleteAFolder",
    "method": "DELETE",
    "path": "/api/v1/folders/{id}",
    "tag": "Folders"
  },
  {
    "name": "listImageVariants",
    "method": "GET",
    "path": "/api/v1/files/{id}/variants",
    "tag": "Images"
  },
  {
    "name": "deleteCachedImageVariants",
    "method": "DELETE",
    "path": "/api/v1/files/{id}/variants",
    "tag": "Images"
  },
  {
    "name": "signAnImageTransformationUrl",
    "method": "POST",
    "path": "/api/v1/images/sign",
    "tag": "Images"
  },
  {
    "name": "listMediaRenditions",
    "method": "GET",
    "path": "/api/v1/files/{id}/media",
    "tag": "Media"
  },
  {
    "name": "generateMediaRenditions",
    "method": "POST",
    "path": "/api/v1/files/{id}/media/process",
    "tag": "Media"
  },
  {
    "name": "createAShareLink",
    "method": "POST",
    "path": "/api/v1/files/{id}/shares",
    "tag": "Shares"
  },
  {
    "name": "listShareLinks",
    "method": "GET",
    "path": "/api/v1/shares",
    "tag": "Shares"
  },
  {
    "name": "getAShareLinkWithItsAccessLog",
    "method": "GET",
    "path": "/api/v1/shares/{id}",
    "tag": "Shares"
  },
  {
    "name": "updateAShareLink",
    "method": "PATCH",
    "path": "/api/v1/shares/{id}",
    "tag": "Shares"
  },
  {
    "name": "revokeAShareLink",
    "method": "POST",
    "path": "/api/v1/shares/{id}/revoke",
    "tag": "Shares"
  },
  {
    "name": "createASignedUrl",
    "method": "POST",
    "path": "/api/v1/files/{id}/signed-url",
    "tag": "Signed URLs"
  },
  {
    "name": "uploadOneOrMoreFiles",
    "method": "POST",
    "path": "/api/v1/uploads",
    "tag": "Uploads"
  },
  {
    "name": "getUploadStatus",
    "method": "GET",
    "path": "/api/v1/uploads/{id}",
    "tag": "Uploads"
  },
  {
    "name": "abortAChunkedUpload",
    "method": "DELETE",
    "path": "/api/v1/uploads/{id}",
    "tag": "Uploads"
  },
  {
    "name": "uploadAChunk",
    "method": "POST",
    "path": "/api/v1/uploads/{id}/chunk",
    "tag": "Uploads"
  },
  {
    "name": "completeAChunkedUpload",
    "method": "POST",
    "path": "/api/v1/uploads/{id}/complete",
    "tag": "Uploads"
  },
  {
    "name": "startAChunkedResumableUpload",
    "method": "POST",
    "path": "/api/v1/uploads/init",
    "tag": "Uploads"
  },
  {
    "name": "usageForAScope",
    "method": "GET",
    "path": "/api/v1/usage",
    "tag": "Usage"
  },
  {
    "name": "restoreAFileFromTheRecycleBin",
    "method": "POST",
    "path": "/api/v1/files/{id}/restore",
    "tag": "Versions"
  },
  {
    "name": "listFileRevisions",
    "method": "GET",
    "path": "/api/v1/files/{id}/versions",
    "tag": "Versions"
  },
  {
    "name": "uploadANewRevision",
    "method": "POST",
    "path": "/api/v1/files/{id}/versions",
    "tag": "Versions"
  },
  {
    "name": "deleteARevision",
    "method": "DELETE",
    "path": "/api/v1/files/{id}/versions/{version}",
    "tag": "Versions"
  },
  {
    "name": "rollBackToARevision",
    "method": "POST",
    "path": "/api/v1/files/{id}/versions/{version}/restore",
    "tag": "Versions"
  },
  {
    "name": "listTheRecycleBin",
    "method": "GET",
    "path": "/api/v1/trash",
    "tag": "Versions"
  },
  {
    "name": "permanentlyDeleteAFileFromTheRecycleBin",
    "method": "DELETE",
    "path": "/api/v1/trash/{id}",
    "tag": "Versions"
  },
  {
    "name": "makeADomainPrimary",
    "method": "PATCH",
    "path": "/api/v1/domains/{id}",
    "tag": "Zones"
  },
  {
    "name": "removeADomain",
    "method": "DELETE",
    "path": "/api/v1/domains/{id}",
    "tag": "Zones"
  },
  {
    "name": "runADomainHealthCheck",
    "method": "POST",
    "path": "/api/v1/domains/{id}/check",
    "tag": "Zones"
  },
  {
    "name": "verifyADomain",
    "method": "POST",
    "path": "/api/v1/domains/{id}/verify",
    "tag": "Zones"
  },
  {
    "name": "listProjects",
    "method": "GET",
    "path": "/api/v1/projects",
    "tag": "Zones"
  },
  {
    "name": "listZones",
    "method": "GET",
    "path": "/api/v1/zones",
    "tag": "Zones"
  },
  {
    "name": "createAZone",
    "method": "POST",
    "path": "/api/v1/zones",
    "tag": "Zones"
  },
  {
    "name": "getAZone",
    "method": "GET",
    "path": "/api/v1/zones/{id}",
    "tag": "Zones"
  },
  {
    "name": "updateAZone",
    "method": "PATCH",
    "path": "/api/v1/zones/{id}",
    "tag": "Zones"
  },
  {
    "name": "addACustomDomain",
    "method": "POST",
    "path": "/api/v1/zones/{id}/domains",
    "tag": "Zones"
  },
  {
    "name": "replicationStatus",
    "method": "GET",
    "path": "/api/v1/zones/{id}/replication",
    "tag": "Zones"
  }
] as const;
