#!/usr/bin/env node
/**
 * Generates the official SDKs from the OpenAPI document produced by the route declarations.
 *
 *   npm run sdk:generate            # exports docs/openapi.json, then generates all SDKs
 *   node scripts/generate-sdks.mjs --spec docs/openapi.json   # generate from an existing spec
 *
 * Outputs (do not edit by hand):
 *   packages/sdk-js/src/generated.ts
 *   sdks/python/cdnpanel/_generated.py
 *   sdks/go/cdnpanel/generated.go
 *
 * Only operations callable with an API key (bearerAuth) are included; staff-only endpoints
 * need a dashboard session and are not part of the SDKs.
 */
import { execFileSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
const specArg = args.indexOf('--spec');
let specPath = specArg !== -1 ? path.resolve(args[specArg + 1]) : path.join(root, 'docs', 'openapi.json');

if (specArg === -1) {
  // Export a fresh document from the route definitions (placeholder secrets: nothing connects anywhere).
  fs.mkdirSync(path.dirname(specPath), { recursive: true });
  execFileSync(process.execPath, ['--import', 'tsx', 'apps/api/src/scripts/export-openapi.ts', specPath], {
    cwd: root,
    stdio: 'inherit',
    env: {
      ...process.env,
      NODE_ENV: 'development',
      APP_URL: 'https://cdn.example.com',
      CDN_URL: 'https://cdn.example.com',
      API_URL: 'https://cdn.example.com',
      DATABASE_URL: 'postgresql://unused',
      REDIS_URL: 'redis://unused',
      SESSION_SECRET: randomBytes(48).toString('base64url'),
      MASTER_ENCRYPTION_KEY: randomBytes(32).toString('base64'),
      LOG_LEVEL: 'silent',
    },
  });
}

const spec = JSON.parse(fs.readFileSync(specPath, 'utf8'));
const HEADER = 'Code generated by scripts/generate-sdks.mjs from the OpenAPI document. DO NOT EDIT.';

// ─── Collect operations ──────────────────────────────────────────────────────

const words = (s) => s.replace(/[’']/g, '').split(/[^A-Za-z0-9]+/).filter(Boolean);
const camel = (s) => words(s).map((w, i) => (i === 0 ? w.toLowerCase() : w[0].toUpperCase() + w.slice(1).toLowerCase())).join('');
const pascal = (s) => words(s).map((w) => w[0].toUpperCase() + w.slice(1).toLowerCase()).join('');
const snake = (s) => words(s).map((w) => w.toLowerCase()).join('_');

const ops = [];
const used = new Set();
for (const [p, methods] of Object.entries(spec.paths)) {
  for (const [method, op] of Object.entries(methods)) {
    const bearer = (op.security ?? []).some((s) => 'bearerAuth' in s);
    if (!bearer || !p.startsWith('/api/v1/')) continue;
    let name = camel(op.summary);
    for (let i = 2; used.has(name); i++) name = `${camel(op.summary)}${i}`;
    used.add(name);
    const pathParams = (op.parameters ?? []).filter((x) => x.in === 'path').map((x) => x.name);
    const queryParams = (op.parameters ?? []).filter((x) => x.in === 'query').map((x) => ({ name: x.name, description: x.description ?? '' }));
    const content = op.requestBody?.content ?? {};
    ops.push({
      name,
      method: method.toUpperCase(),
      path: p,
      summary: op.summary,
      description: (op.description ?? '').split('\n')[0],
      tag: op.tags?.[0] ?? 'Other',
      scopes: (op.security ?? []).find((s) => 'bearerAuth' in s)?.bearerAuth ?? [],
      pathParams,
      queryParams,
      json: Boolean(content['application/json']),
      multipart: Boolean(content['multipart/form-data']),
      raw: Boolean(content['application/octet-stream']),
      binary: Object.values(op.responses ?? {}).some((r) => r.content && !r.content['application/json'] && Object.keys(r.content).length > 0),
    });
  }
}
ops.sort((a, b) => a.tag.localeCompare(b.tag) || a.path.localeCompare(b.path));
const safeId = (n) => n.replace(/[^A-Za-z0-9_]/g, '_');

// ─── TypeScript ──────────────────────────────────────────────────────────────

function genTs() {
  const lines = [`// ${HEADER}`, `import { CdnCore, type RequestOptions } from './core.js';`, '', '/** CDNPanel API client. Every method maps to one REST endpoint. */', 'export class CdnClient extends CdnCore {'];
  for (const op of ops) {
    const args = op.pathParams.map((n) => `${safeId(n)}: string`);
    const opts = [];
    if (op.queryParams.length) opts.push(`query?: { ${op.queryParams.map((q) => `${JSON.stringify(q.name)}?: string | number | boolean`).join('; ')} }`);
    if (op.json) opts.push('body?: Record<string, unknown>');
    if (op.multipart) opts.push('form: FormData');
    if (op.raw) opts.push('data: Uint8Array | Blob');
    args.push(`options: { ${opts.join('; ')}${opts.length ? '; ' : ''}signal?: AbortSignal }${op.multipart || op.raw ? '' : ' = {}'}`);
    const urlExpr = '`' + op.path.replace(/\{(\w+)\}/g, (_, n) => '${encodeURIComponent(' + safeId(n) + ')}') + '`';
    lines.push(`  /**`, `   * ${op.summary}${op.description && op.description !== op.summary ? ` — ${op.description.replace(/\*\//g, '* /')}` : ''}`, `   * \`${op.method} ${op.path}\`${op.scopes.length ? ` · scopes: ${op.scopes.join(', ')}` : ''}`, `   */`);
    const reqOpts = [`method: '${op.method}'`, 'signal: options.signal'];
    if (op.queryParams.length) reqOpts.push('query: options.query');
    if (op.json) reqOpts.push('body: options.body');
    if (op.multipart) reqOpts.push('form: options.form');
    if (op.raw) reqOpts.push('raw: options.data');
    if (op.binary) reqOpts.push("responseType: 'response'");
    lines.push(`  ${op.name}<T = ${op.binary ? 'Response' : 'any'}>(${args.join(', ')}): Promise<T> {`, `    return this.request<T>(${urlExpr}, { ${reqOpts.join(', ')} } as RequestOptions);`, '  }', '');
  }
  lines.push('}', '', `export const OPERATIONS = ${JSON.stringify(ops.map((o) => ({ name: o.name, method: o.method, path: o.path, tag: o.tag })), null, 2)} as const;`, '');
  return lines.join('\n');
}

// ─── Python ──────────────────────────────────────────────────────────────────

function genPy() {
  const lines = [
    `# ${HEADER}`,
    '# ruff: noqa: E501',
    'from typing import Any, Dict, Optional',
    'from urllib.parse import quote as _quote',
    '',
    'from ._core import CdnCore',
    '',
    '',
    'def _q(v: str) -> str:',
    '    return _quote(str(v), safe="")',
    '',
    '',
    'class CdnClient(CdnCore):',
    '    """CDNPanel API client. Every method maps to one REST endpoint."""',
    '',
  ];
  for (const op of ops) {
    const params = ['self', ...op.pathParams.map((n) => `${snake(n)}: str`)];
    if (op.multipart) params.push('files: Dict[str, Any]', 'fields: Optional[Dict[str, str]] = None');
    if (op.raw) params.push('data: bytes');
    if (op.json) params.push('body: Optional[Dict[str, Any]] = None');
    if (op.queryParams.length) params.push('query: Optional[Dict[str, Any]] = None');
    const pathExpr = 'f"' + op.path.replace(/\{(\w+)\}/g, (_, n) => '{_q(' + snake(n) + ')}') + '"';
    lines.push(`    def ${op.name.replace(/([A-Z])/g, '_$1').toLowerCase()}(${params.join(', ')}) -> Any:`, `        """${op.summary.replace(/"/g, "'")} (${op.method} ${op.path})."""`);
    const kw = [`"${op.method}"`, pathExpr];
    if (op.queryParams.length) kw.push('query=query');
    if (op.json) kw.push('body=body');
    if (op.multipart) kw.push('files=files', 'fields=fields');
    if (op.raw) kw.push('data=data');
    if (op.binary) kw.push('raw_response=True');
    lines.push(`        return self._request(${kw.join(', ')})`, '');
  }
  return lines.join('\n');
}

// ─── Go ──────────────────────────────────────────────────────────────────────

function genGo() {
  const lines = [`// ${HEADER}`, '', 'package cdnpanel', '', 'import (', '\t"context"', '\t"fmt"', '\t"net/url"', ')', '', 'var _ = fmt.Sprintf', ''];
  for (const op of ops) {
    const name = pascal(op.name.replace(/([A-Z])/g, ' $1'));
    const params = ['ctx context.Context', ...op.pathParams.map((n) => `${safeId(camel(n))} string`)];
    if (op.queryParams.length) params.push('query url.Values');
    if (op.json) params.push('body any');
    if (op.multipart) params.push('form *Multipart');
    if (op.raw) params.push('data []byte');
    const fmtPath = op.path.replace(/\{(\w+)\}/g, '%s');
    const pathArgs = op.pathParams.map((n) => `url.PathEscape(${safeId(camel(n))})`);
    const pathExpr = pathArgs.length ? `fmt.Sprintf(${JSON.stringify(fmtPath)}, ${pathArgs.join(', ')})` : JSON.stringify(op.path);
    lines.push(`// ${name}: ${op.summary} (${op.method} ${op.path}).`, `func (c *Client) ${name}(${params.join(', ')}) (*Response, error) {`, `\treturn c.do(ctx, ${JSON.stringify(op.method)}, ${pathExpr}, ${op.queryParams.length ? 'query' : 'nil'}, ${op.json ? 'body' : 'nil'}, ${op.multipart ? 'form' : 'nil'}, ${op.raw ? 'data' : 'nil'})`, '}', '');
  }
  return lines.join('\n');
}

const out = [
  ['packages/sdk-js/src/generated.ts', genTs()],
  ['sdks/python/cdnpanel/_generated.py', genPy()],
  ['sdks/go/cdnpanel/generated.go', genGo()],
];
for (const [file, content] of out) {
  const abs = path.join(root, file);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, content);
  console.log(`wrote ${file}`);
}
console.log(`${ops.length} operations`);
